lab3 added
korovinaks/Network-Labs pull request #3
Opened 2020-12-13 20:53 UTC by korovinaks

@Aloomenon
Лаба 3, Коровина Ксения, группа 18205

2020-12-16 20:16 UTC, Aloomenon requested changes
Проверьте, что все закрывате.
Какие кодировки используются при отправке\получении сообщений?
Почитайте Java code conventions.

2020-12-20 18:33 UTC, korovinaks commented
Проверила, все закрываю.
В классе ReadMessagesThread не закрываю Scanner, так как далее следует вечный цикл. В классе SendMessagesThread создаю сокет и после отправки пакета закрываю его. В классе ReceiveMessagesThread не закрываю сокет, так как далее следует вечный цикл, в котором используется этот сокет.

При отправке и получении сообщений у меня используется дефолтная кодировка. Проверила, что она UTF-8 : System.out.println(Charset.defaultCharset().displayName());

По поводу Java code conventions..... Согласна, что не переименовала путь к своей лабе, и методы и переменные называла не в "верблюжьей" нотации, и константы должны быть в верхнем регистре. Учту в следующей(их) работе(ах) :)

2020-12-20 18:55 UTC, korovinaks commented
А нет, увидела незакрытые стримы. Закрыла.

2020-12-29 07:05 UTC, Aloomenon approved these changes
Принял

2020-12-29 16:30 UTC, merged